version: "3.3"
services:
  postgres:
    image: "postgres:14.5"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "todo_list_db"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
    networks:
      - reference
networks:
  reference:
